### ISSUE TITLE
Possible mistake in config schema

### ISSUE THREAD

**Issue by parrangoiz** [awslabs/palace#145] opened 2023-12-12 21:58 UTC
*Description: A clear and concise description of what the bug is.*

Currently the `config/model.json` schema simultaneously allows `UniformLevels` and `MaxIts` to be contained in the `Refinement` object, but it's unclear as a user what behavior to expect; I'd imagine the former triggers uniform refinement whereas the latter triggers AMR.

@hughcars 

*To reproduce: Please provide minimal example that reproduces the error. For existing
examples, please provide a link.*

*Error message: Paste the complete error message or log, if applicable.*

*Environment: Any environment details, such as operating system, compiler, etc.*

**Comment by sebastiangrimberg** [comment] 2023-12-12 22:04
This is intended behavior, it's valid to consider the "starting point" for AMR as a mesh with a certain number of levels of uniform refinement. I'm not sure it is a good idea, but it is a valid one. Is there a problem you experienced?

**Comment by parrangoiz** [comment] 2023-12-12 22:50
No, no problems. Just confusion on my side as I thought these two refinement modes couldn't be performed in the same job. This could be made clearer in the docs. But ok, it totally makes sense that it should be possible to do uniform refinement prior to adaptive.

**Comment by sebastiangrimberg** [comment] 2023-12-19 17:09
Closed by https://github.com/awslabs/palace/pull/146

**Closed by sebastiangrimberg** 2023-12-19 17:09 UTC
Labels: documentation, amr
